name: mindmate
description: MindMate Flutter application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_tts: ^4.2.5
  rename_app: ^1.6.6
  speech_to_text: ^7.4.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
